# While Expo doesn't require hoisted anymore, Electron still needs it.
# https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#initializing-your-npm-project
nodeLinker: hoisted
minimumReleaseAge: 0

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  react-native-nitro-modules: true
  sharp: true
  unrs-resolver: true

packages:
  - apps/*
  - packages/*
  - examples/*

catalogs:
  react19:
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

patchedDependencies:
  vitest-mobile@0.4.3: patches/vitest-mobile@0.4.3.patch
