# While Expo doesn't require hoisted anymore, Electron still needs it.
# https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#initializing-your-npm-project
nodeLinker: hoisted
minimumReleaseAge: 0

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  react-native-nitro-modules: true
  sharp: true
  unrs-resolver: true

packages:
  - apps/*
  - packages/*
  - examples/*
  - scripts/typescript6

overrides:
  react: 19.2.3
  react-dom: 19.2.3

catalogs:
  react19:
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    react: 19.2.3
    react-dom: 19.2.3

patchedDependencies:
  "@next/mdx@16.2.11": patches/@next__mdx@16.2.11.patch
  '@paulmillr/jsbt@0.6.1': patches/@paulmillr__jsbt@0.6.1.patch
  vitest-mobile@0.4.3: patches/vitest-mobile@0.4.3.patch
