import { Brand, Context, Effect } from "effect";
import { NodeId } from "./Timestamp.js";

export const customAlphabetForNodeId = "0123456789abcdef";

export interface Crypto {
  readonly makeNodeId: Effect.Effect<never, never, NodeId>;

  readonly makeMnemonic: Effect.Effect<never, never, Mnemonic>;

  // muze bejt async, nejde to znova? ne
  // mnemonicToSeedSync
}

export const Crypto = Context.Tag<Crypto>();

/**
 * Mnemonic is a password generated by Evolu in BIP39 format.
 *
 * A mnemonic, also known as a "seed phrase," is a set of 12 words in a
 * specific order chosen from a predefined list. The purpose of the BIP39
 * mnemonic is to provide a human-readable way of storing a private key.
 */
export type Mnemonic = string & Brand.Brand<"Mnemonic">;
