/* eslint-disable */
// @generated by protobuf-ts 2.9.0 with parameter eslint_disable
// @generated from protobuf file "Protobuf.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message MessageContent
 */
export interface MessageContent {
  /**
   * @generated from protobuf field: string table = 1;
   */
  table: string;
  /**
   * @generated from protobuf field: string row = 2;
   */
  row: string;
  /**
   * @generated from protobuf field: string column = 3;
   */
  column: string;
  /**
   * @generated from protobuf oneof: value
   */
  value:
    | {
        oneofKind: "stringValue";
        /**
         * @generated from protobuf field: string stringValue = 4;
         */
        stringValue: string;
      }
    | {
        oneofKind: "numberValue";
        /**
         * @generated from protobuf field: int32 numberValue = 5;
         */
        numberValue: number;
      }
    | {
        oneofKind: "bytesValue";
        /**
         * @generated from protobuf field: bytes bytesValue = 6;
         */
        bytesValue: Uint8Array;
      }
    | {
        oneofKind: undefined;
      };
}
/**
 * @generated from protobuf message EncryptedMessage
 */
export interface EncryptedMessage {
  /**
   * @generated from protobuf field: string timestamp = 1;
   */
  timestamp: string;
  /**
   * @generated from protobuf field: bytes content = 2;
   */
  content: Uint8Array;
}
/**
 * @generated from protobuf message SyncRequest
 */
export interface SyncRequest {
  /**
   * @generated from protobuf field: repeated EncryptedMessage messages = 1;
   */
  messages: EncryptedMessage[];
  /**
   * @generated from protobuf field: string userId = 2;
   */
  userId: string;
  /**
   * @generated from protobuf field: string nodeId = 3;
   */
  nodeId: string;
  /**
   * @generated from protobuf field: string merkleTree = 4;
   */
  merkleTree: string;
}
/**
 * @generated from protobuf message SyncResponse
 */
export interface SyncResponse {
  /**
   * @generated from protobuf field: repeated EncryptedMessage messages = 1;
   */
  messages: EncryptedMessage[];
  /**
   * @generated from protobuf field: string merkleTree = 2;
   */
  merkleTree: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class MessageContent$Type extends MessageType<MessageContent> {
  constructor() {
    super("MessageContent", [
      { no: 1, name: "table", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "row", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 3, name: "column", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      {
        no: 4,
        name: "stringValue",
        kind: "scalar",
        oneof: "value",
        T: 9 /*ScalarType.STRING*/,
      },
      {
        no: 5,
        name: "numberValue",
        kind: "scalar",
        oneof: "value",
        T: 5 /*ScalarType.INT32*/,
      },
      {
        no: 6,
        name: "bytesValue",
        kind: "scalar",
        oneof: "value",
        T: 12 /*ScalarType.BYTES*/,
      },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message MessageContent
 */
export const MessageContent = new MessageContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EncryptedMessage$Type extends MessageType<EncryptedMessage> {
  constructor() {
    super("EncryptedMessage", [
      { no: 1, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "content", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message EncryptedMessage
 */
export const EncryptedMessage = new EncryptedMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncRequest$Type extends MessageType<SyncRequest> {
  constructor() {
    super("SyncRequest", [
      {
        no: 1,
        name: "messages",
        kind: "message",
        repeat: 1 /*RepeatType.PACKED*/,
        T: () => EncryptedMessage,
      },
      { no: 2, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 3, name: "nodeId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 4, name: "merkleTree", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message SyncRequest
 */
export const SyncRequest = new SyncRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncResponse$Type extends MessageType<SyncResponse> {
  constructor() {
    super("SyncResponse", [
      {
        no: 1,
        name: "messages",
        kind: "message",
        repeat: 1 /*RepeatType.PACKED*/,
        T: () => EncryptedMessage,
      },
      { no: 2, name: "merkleTree", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message SyncResponse
 */
export const SyncResponse = new SyncResponse$Type();
