export type { Brand } from "../../../../packages/common/src/Brand.ts";
export { err, ok, type Result } from "../../../../packages/common/src/Result.ts";
export {
  BigInt,
  Function,
  FiniteNumber,
  NonEmptyTrimmedString100,
  Number,
  String,
  array,
  assertType,
  brand,
  capitalized,
  createInstanceOfType,
  discriminatedUnion,
  int,
  lessThan,
  lazy,
  literal,
  localizeTypes,
  maxLength,
  minLength,
  multipleOf,
  object,
  optional,
  PositiveDecimalString,
  record,
  regex,
  transform,
  tuple,
  typed,
  undefinedOr,
  union,
  type ArrayElementsError,
  type ArrayError,
  type BrandFactory,
  type LazyType,
  type MinLengthError,
  type ObjectError,
  type TypeError,
  type TypeOfError,
  type ValidateBrandFactoryNumber,
} from "../../../../packages/common/src/Type2.ts";
