services:
  evolu-relay:
    image: docker.io/evoluhq/relay:4
    ports:
      - "4000:4000"
    # environment:
    #   EVOLU_RELAY_MAX_OWNER_BYTES: "10MiB"
    volumes:
      - evolu-relay-data:/app/data
    restart: unless-stopped

volumes:
  evolu-relay-data:
    name: evolu-relay-data
