/**
 * SQLite's constants and the facts of one wasm build.
 *
 * Generated by `scripts/generate.mts` from the string
 * `sqlite3__wasm_enum_json()` returns and the binary's exports, pinned in
 * `scripts/upstream/sqlite3-wasm-enum.json` and
 * `scripts/upstream/sqlite3-wasm-exports.json`. Do not edit.
 *
 * SQLite's constants never change, but {@link SQLITE_WASM_DEALLOC}, the struct
 * layouts and the version belong to the build. The loader fails unless the
 * binary it loads has the {@link sqliteWasmBuildHash} of the pinned one, so
 * these values always describe the binary that runs.
 *
 * @module
 */

import type { SqliteFunctionPtr } from "./Pointer.ts";

// Result codes.
export const SQLITE_OK = 0;
export const SQLITE_ERROR = 1;
export const SQLITE_INTERNAL = 2;
export const SQLITE_PERM = 3;
export const SQLITE_ABORT = 4;
export const SQLITE_BUSY = 5;
export const SQLITE_LOCKED = 6;
export const SQLITE_NOMEM = 7;
export const SQLITE_READONLY = 8;
export const SQLITE_INTERRUPT = 9;
export const SQLITE_IOERR = 10;
export const SQLITE_CORRUPT = 11;
export const SQLITE_NOTFOUND = 12;
export const SQLITE_FULL = 13;
export const SQLITE_CANTOPEN = 14;
export const SQLITE_PROTOCOL = 15;
export const SQLITE_EMPTY = 16;
export const SQLITE_SCHEMA = 17;
export const SQLITE_TOOBIG = 18;
export const SQLITE_CONSTRAINT = 19;
export const SQLITE_MISMATCH = 20;
export const SQLITE_MISUSE = 21;
export const SQLITE_NOLFS = 22;
export const SQLITE_AUTH = 23;
export const SQLITE_FORMAT = 24;
export const SQLITE_RANGE = 25;
export const SQLITE_NOTADB = 26;
export const SQLITE_NOTICE = 27;
export const SQLITE_WARNING = 28;
export const SQLITE_ROW = 100;
export const SQLITE_DONE = 101;
export const SQLITE_ERROR_MISSING_COLLSEQ = 257;
export const SQLITE_ERROR_RETRY = 513;
export const SQLITE_ERROR_SNAPSHOT = 769;
export const SQLITE_IOERR_READ = 266;
export const SQLITE_IOERR_SHORT_READ = 522;
export const SQLITE_IOERR_WRITE = 778;
export const SQLITE_IOERR_FSYNC = 1034;
export const SQLITE_IOERR_DIR_FSYNC = 1290;
export const SQLITE_IOERR_TRUNCATE = 1546;
export const SQLITE_IOERR_FSTAT = 1802;
export const SQLITE_IOERR_UNLOCK = 2058;
export const SQLITE_IOERR_RDLOCK = 2314;
export const SQLITE_IOERR_DELETE = 2570;
export const SQLITE_IOERR_BLOCKED = 2826;
export const SQLITE_IOERR_NOMEM = 3082;
export const SQLITE_IOERR_ACCESS = 3338;
export const SQLITE_IOERR_CHECKRESERVEDLOCK = 3594;
export const SQLITE_IOERR_LOCK = 3850;
export const SQLITE_IOERR_CLOSE = 4106;
export const SQLITE_IOERR_DIR_CLOSE = 4362;
export const SQLITE_IOERR_SHMOPEN = 4618;
export const SQLITE_IOERR_SHMSIZE = 4874;
export const SQLITE_IOERR_SHMLOCK = 5130;
export const SQLITE_IOERR_SHMMAP = 5386;
export const SQLITE_IOERR_SEEK = 5642;
export const SQLITE_IOERR_DELETE_NOENT = 5898;
export const SQLITE_IOERR_MMAP = 6154;
export const SQLITE_IOERR_GETTEMPPATH = 6410;
export const SQLITE_IOERR_CONVPATH = 6666;
export const SQLITE_IOERR_VNODE = 6922;
export const SQLITE_IOERR_AUTH = 7178;
export const SQLITE_IOERR_BEGIN_ATOMIC = 7434;
export const SQLITE_IOERR_COMMIT_ATOMIC = 7690;
export const SQLITE_IOERR_ROLLBACK_ATOMIC = 7946;
export const SQLITE_IOERR_DATA = 8202;
export const SQLITE_IOERR_CORRUPTFS = 8458;
export const SQLITE_LOCKED_SHAREDCACHE = 262;
export const SQLITE_LOCKED_VTAB = 518;
export const SQLITE_BUSY_RECOVERY = 261;
export const SQLITE_BUSY_SNAPSHOT = 517;
export const SQLITE_BUSY_TIMEOUT = 773;
export const SQLITE_CANTOPEN_NOTEMPDIR = 270;
export const SQLITE_CANTOPEN_ISDIR = 526;
export const SQLITE_CANTOPEN_FULLPATH = 782;
export const SQLITE_CANTOPEN_CONVPATH = 1038;
export const SQLITE_CANTOPEN_SYMLINK = 1550;
export const SQLITE_CORRUPT_VTAB = 267;
export const SQLITE_CORRUPT_SEQUENCE = 523;
export const SQLITE_CORRUPT_INDEX = 779;
export const SQLITE_READONLY_RECOVERY = 264;
export const SQLITE_READONLY_CANTLOCK = 520;
export const SQLITE_READONLY_ROLLBACK = 776;
export const SQLITE_READONLY_DBMOVED = 1032;
export const SQLITE_READONLY_CANTINIT = 1288;
export const SQLITE_READONLY_DIRECTORY = 1544;
export const SQLITE_ABORT_ROLLBACK = 516;
export const SQLITE_CONSTRAINT_CHECK = 275;
export const SQLITE_CONSTRAINT_COMMITHOOK = 531;
export const SQLITE_CONSTRAINT_FOREIGNKEY = 787;
export const SQLITE_CONSTRAINT_FUNCTION = 1043;
export const SQLITE_CONSTRAINT_NOTNULL = 1299;
export const SQLITE_CONSTRAINT_PRIMARYKEY = 1555;
export const SQLITE_CONSTRAINT_TRIGGER = 1811;
export const SQLITE_CONSTRAINT_UNIQUE = 2067;
export const SQLITE_CONSTRAINT_VTAB = 2323;
export const SQLITE_CONSTRAINT_ROWID = 2579;
export const SQLITE_CONSTRAINT_PINNED = 2835;
export const SQLITE_CONSTRAINT_DATATYPE = 3091;
export const SQLITE_NOTICE_RECOVER_WAL = 283;
export const SQLITE_NOTICE_RECOVER_ROLLBACK = 539;
export const SQLITE_WARNING_AUTOINDEX = 284;
export const SQLITE_AUTH_USER = 279;
export const SQLITE_OK_LOAD_PERMANENTLY = 256;

// Fundamental data types.
export const SQLITE_INTEGER = 1;
export const SQLITE_FLOAT = 2;
export const SQLITE_TEXT = 3;
export const SQLITE_BLOB = 4;
export const SQLITE_NULL = 5;

// Flags for sqlite3_open_v2 and the VFS xOpen method.
export const SQLITE_OPEN_READONLY = 1;
export const SQLITE_OPEN_READWRITE = 2;
export const SQLITE_OPEN_CREATE = 4;
export const SQLITE_OPEN_URI = 64;
export const SQLITE_OPEN_MEMORY = 128;
export const SQLITE_OPEN_NOMUTEX = 32768;
export const SQLITE_OPEN_FULLMUTEX = 65536;
export const SQLITE_OPEN_SHAREDCACHE = 131072;
export const SQLITE_OPEN_PRIVATECACHE = 262144;
export const SQLITE_OPEN_EXRESCODE = 33554432;
export const SQLITE_OPEN_NOFOLLOW = 16777216;
export const SQLITE_OPEN_MAIN_DB = 256;
export const SQLITE_OPEN_MAIN_JOURNAL = 2048;
export const SQLITE_OPEN_TEMP_DB = 512;
export const SQLITE_OPEN_TEMP_JOURNAL = 4096;
export const SQLITE_OPEN_TRANSIENT_DB = 1024;
export const SQLITE_OPEN_SUBJOURNAL = 8192;
export const SQLITE_OPEN_SUPER_JOURNAL = 16384;
export const SQLITE_OPEN_WAL = 524288;
export const SQLITE_OPEN_DELETEONCLOSE = 8;
export const SQLITE_OPEN_EXCLUSIVE = 16;

// Flags for sqlite3_prepare_v3.
export const SQLITE_PREPARE_PERSISTENT = 1;
export const SQLITE_PREPARE_NORMALIZE = 2;
export const SQLITE_PREPARE_NO_VTAB = 4;
export const SQLITE_PREPARE_FROM_DDL = 32;

// Counters for sqlite3_stmt_status.
export const SQLITE_STMTSTATUS_FULLSCAN_STEP = 1;
export const SQLITE_STMTSTATUS_SORT = 2;
export const SQLITE_STMTSTATUS_AUTOINDEX = 3;
export const SQLITE_STMTSTATUS_VM_STEP = 4;
export const SQLITE_STMTSTATUS_REPREPARE = 5;
export const SQLITE_STMTSTATUS_RUN = 6;
export const SQLITE_STMTSTATUS_FILTER_MISS = 7;
export const SQLITE_STMTSTATUS_FILTER_HIT = 8;
export const SQLITE_STMTSTATUS_MEMUSED = 99;

// Limit categories for sqlite3_limit.
export const SQLITE_LIMIT_LENGTH = 0;
export const SQLITE_LIMIT_SQL_LENGTH = 1;
export const SQLITE_LIMIT_COLUMN = 2;
export const SQLITE_LIMIT_EXPR_DEPTH = 3;
export const SQLITE_LIMIT_COMPOUND_SELECT = 4;
export const SQLITE_LIMIT_VDBE_OP = 5;
export const SQLITE_LIMIT_FUNCTION_ARG = 6;
export const SQLITE_LIMIT_ATTACHED = 7;
export const SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8;
export const SQLITE_LIMIT_VARIABLE_NUMBER = 9;
export const SQLITE_LIMIT_TRIGGER_DEPTH = 10;
export const SQLITE_LIMIT_WORKER_THREADS = 11;
export const SQLITE_LIMIT_PARSER_DEPTH = 12;

// Flags for sqlite3_serialize and sqlite3_deserialize.
export const SQLITE_SERIALIZE_NOCOPY = 1;
export const SQLITE_DESERIALIZE_FREEONCLOSE = 1;
export const SQLITE_DESERIALIZE_READONLY = 4;
export const SQLITE_DESERIALIZE_RESIZEABLE = 2;

// Flags for the VFS xAccess method.
export const SQLITE_ACCESS_EXISTS = 0;
export const SQLITE_ACCESS_READWRITE = 1;
export const SQLITE_ACCESS_READ = 2;

// File lock levels for the VFS xLock and xUnlock methods.
export const SQLITE_LOCK_NONE = 0;
export const SQLITE_LOCK_SHARED = 1;
export const SQLITE_LOCK_RESERVED = 2;
export const SQLITE_LOCK_PENDING = 3;
export const SQLITE_LOCK_EXCLUSIVE = 4;

// Flags for the VFS xSync method.
export const SQLITE_SYNC_NORMAL = 2;
export const SQLITE_SYNC_FULL = 3;
export const SQLITE_SYNC_DATAONLY = 16;

// Device characteristics for the VFS xDeviceCharacteristics method.
export const SQLITE_IOCAP_ATOMIC = 1;
export const SQLITE_IOCAP_ATOMIC512 = 2;
export const SQLITE_IOCAP_ATOMIC1K = 4;
export const SQLITE_IOCAP_ATOMIC2K = 8;
export const SQLITE_IOCAP_ATOMIC4K = 16;
export const SQLITE_IOCAP_ATOMIC8K = 32;
export const SQLITE_IOCAP_ATOMIC16K = 64;
export const SQLITE_IOCAP_ATOMIC32K = 128;
export const SQLITE_IOCAP_ATOMIC64K = 256;
export const SQLITE_IOCAP_SAFE_APPEND = 512;
export const SQLITE_IOCAP_SEQUENTIAL = 1024;
export const SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN = 2048;
export const SQLITE_IOCAP_POWERSAFE_OVERWRITE = 4096;
export const SQLITE_IOCAP_IMMUTABLE = 8192;
export const SQLITE_IOCAP_BATCH_ATOMIC = 16384;

// Opcodes for sqlite3_file_control and the VFS xFileControl method.
export const SQLITE_FCNTL_LOCKSTATE = 1;
export const SQLITE_FCNTL_GET_LOCKPROXYFILE = 2;
export const SQLITE_FCNTL_SET_LOCKPROXYFILE = 3;
export const SQLITE_FCNTL_LAST_ERRNO = 4;
export const SQLITE_FCNTL_SIZE_HINT = 5;
export const SQLITE_FCNTL_CHUNK_SIZE = 6;
export const SQLITE_FCNTL_FILE_POINTER = 7;
export const SQLITE_FCNTL_SYNC_OMITTED = 8;
export const SQLITE_FCNTL_WIN32_AV_RETRY = 9;
export const SQLITE_FCNTL_PERSIST_WAL = 10;
export const SQLITE_FCNTL_OVERWRITE = 11;
export const SQLITE_FCNTL_VFSNAME = 12;
export const SQLITE_FCNTL_POWERSAFE_OVERWRITE = 13;
export const SQLITE_FCNTL_PRAGMA = 14;
export const SQLITE_FCNTL_BUSYHANDLER = 15;
export const SQLITE_FCNTL_TEMPFILENAME = 16;
export const SQLITE_FCNTL_MMAP_SIZE = 18;
export const SQLITE_FCNTL_TRACE = 19;
export const SQLITE_FCNTL_HAS_MOVED = 20;
export const SQLITE_FCNTL_SYNC = 21;
export const SQLITE_FCNTL_COMMIT_PHASETWO = 22;
export const SQLITE_FCNTL_WIN32_SET_HANDLE = 23;
export const SQLITE_FCNTL_WAL_BLOCK = 24;
export const SQLITE_FCNTL_ZIPVFS = 25;
export const SQLITE_FCNTL_RBU = 26;
export const SQLITE_FCNTL_VFS_POINTER = 27;
export const SQLITE_FCNTL_JOURNAL_POINTER = 28;
export const SQLITE_FCNTL_WIN32_GET_HANDLE = 29;
export const SQLITE_FCNTL_PDB = 30;
export const SQLITE_FCNTL_BEGIN_ATOMIC_WRITE = 31;
export const SQLITE_FCNTL_COMMIT_ATOMIC_WRITE = 32;
export const SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE = 33;
export const SQLITE_FCNTL_LOCK_TIMEOUT = 34;
export const SQLITE_FCNTL_DATA_VERSION = 35;
export const SQLITE_FCNTL_SIZE_LIMIT = 36;
export const SQLITE_FCNTL_CKPT_DONE = 37;
export const SQLITE_FCNTL_RESERVE_BYTES = 38;
export const SQLITE_FCNTL_CKPT_START = 39;
export const SQLITE_FCNTL_EXTERNAL_READER = 40;
export const SQLITE_FCNTL_CKSM_FILE = 41;
export const SQLITE_FCNTL_RESET_CACHE = 42;

// Text encodings.
export const SQLITE_UTF8 = 1;
export const SQLITE_UTF8_ZT = 16;
export const SQLITE_UTF16LE = 2;
export const SQLITE_UTF16BE = 3;
export const SQLITE_UTF16 = 4;
export const SQLITE_UTF16_ALIGNED = 8;

// Transaction states sqlite3_txn_state returns.
export const SQLITE_TXN_NONE = 0;
export const SQLITE_TXN_READ = 1;
export const SQLITE_TXN_WRITE = 2;

// Options for sqlite3_config.
export const SQLITE_CONFIG_SINGLETHREAD = 1;
export const SQLITE_CONFIG_MULTITHREAD = 2;
export const SQLITE_CONFIG_SERIALIZED = 3;
export const SQLITE_CONFIG_MALLOC = 4;
export const SQLITE_CONFIG_GETMALLOC = 5;
export const SQLITE_CONFIG_SCRATCH = 6;
export const SQLITE_CONFIG_PAGECACHE = 7;
export const SQLITE_CONFIG_HEAP = 8;
export const SQLITE_CONFIG_MEMSTATUS = 9;
export const SQLITE_CONFIG_MUTEX = 10;
export const SQLITE_CONFIG_GETMUTEX = 11;
export const SQLITE_CONFIG_LOOKASIDE = 13;
export const SQLITE_CONFIG_PCACHE = 14;
export const SQLITE_CONFIG_GETPCACHE = 15;
export const SQLITE_CONFIG_LOG = 16;
export const SQLITE_CONFIG_URI = 17;
export const SQLITE_CONFIG_PCACHE2 = 18;
export const SQLITE_CONFIG_GETPCACHE2 = 19;
export const SQLITE_CONFIG_COVERING_INDEX_SCAN = 20;
export const SQLITE_CONFIG_SQLLOG = 21;
export const SQLITE_CONFIG_MMAP_SIZE = 22;
export const SQLITE_CONFIG_WIN32_HEAPSIZE = 23;
export const SQLITE_CONFIG_PCACHE_HDRSZ = 24;
export const SQLITE_CONFIG_PMASZ = 25;
export const SQLITE_CONFIG_STMTJRNL_SPILL = 26;
export const SQLITE_CONFIG_SMALL_MALLOC = 27;
export const SQLITE_CONFIG_SORTERREF_SIZE = 28;
export const SQLITE_CONFIG_MEMDB_MAXSIZE = 29;

// Options for sqlite3_db_config.
export const SQLITE_DBCONFIG_MAINDBNAME = 1000;
export const SQLITE_DBCONFIG_LOOKASIDE = 1001;
export const SQLITE_DBCONFIG_ENABLE_FKEY = 1002;
export const SQLITE_DBCONFIG_ENABLE_TRIGGER = 1003;
export const SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION = 1005;
export const SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE = 1006;
export const SQLITE_DBCONFIG_ENABLE_QPSG = 1007;
export const SQLITE_DBCONFIG_TRIGGER_EQP = 1008;
export const SQLITE_DBCONFIG_RESET_DATABASE = 1009;
export const SQLITE_DBCONFIG_DEFENSIVE = 1010;
export const SQLITE_DBCONFIG_WRITABLE_SCHEMA = 1011;
export const SQLITE_DBCONFIG_LEGACY_ALTER_TABLE = 1012;
export const SQLITE_DBCONFIG_DQS_DML = 1013;
export const SQLITE_DBCONFIG_DQS_DDL = 1014;
export const SQLITE_DBCONFIG_ENABLE_VIEW = 1015;
export const SQLITE_DBCONFIG_LEGACY_FILE_FORMAT = 1016;
export const SQLITE_DBCONFIG_TRUSTED_SCHEMA = 1017;
export const SQLITE_DBCONFIG_STMT_SCANSTATUS = 1018;
export const SQLITE_DBCONFIG_REVERSE_SCANORDER = 1019;
export const SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE = 1020;
export const SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE = 1021;
export const SQLITE_DBCONFIG_ENABLE_COMMENTS = 1022;
export const SQLITE_DBCONFIG_MAX = 1023;
export const SQLITE_DBCONFIG_FP_DIGITS = 1023;

// Counters for sqlite3_status and sqlite3_status64.
export const SQLITE_STATUS_MEMORY_USED = 0;
export const SQLITE_STATUS_PAGECACHE_USED = 1;
export const SQLITE_STATUS_PAGECACHE_OVERFLOW = 2;
export const SQLITE_STATUS_MALLOC_SIZE = 5;
export const SQLITE_STATUS_PARSER_STACK = 6;
export const SQLITE_STATUS_PAGECACHE_SIZE = 7;
export const SQLITE_STATUS_MALLOC_COUNT = 9;

// Counters for sqlite3_db_status and sqlite3_db_status64.
export const SQLITE_DBSTATUS_LOOKASIDE_USED = 0;
export const SQLITE_DBSTATUS_CACHE_USED = 1;
export const SQLITE_DBSTATUS_SCHEMA_USED = 2;
export const SQLITE_DBSTATUS_STMT_USED = 3;
export const SQLITE_DBSTATUS_LOOKASIDE_HIT = 4;
export const SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE = 5;
export const SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL = 6;
export const SQLITE_DBSTATUS_CACHE_HIT = 7;
export const SQLITE_DBSTATUS_CACHE_MISS = 8;
export const SQLITE_DBSTATUS_CACHE_WRITE = 9;
export const SQLITE_DBSTATUS_DEFERRED_FKS = 10;
export const SQLITE_DBSTATUS_CACHE_USED_SHARED = 11;
export const SQLITE_DBSTATUS_CACHE_SPILL = 12;
export const SQLITE_DBSTATUS_TEMPBUF_SPILL = 13;
export const SQLITE_DBSTATUS_MAX = 13;

// Flags for sqlite3_create_function_v2.
export const SQLITE_DETERMINISTIC = 2048;
export const SQLITE_DIRECTONLY = 524288;
export const SQLITE_INNOCUOUS = 2097152;
export const SQLITE_SUBTYPE = 1048576;
export const SQLITE_RESULT_SUBTYPE = 16777216;
export const SQLITE_SELFORDER1 = 33554432;

// Authorizer action codes and results, and update hook operations.
export const SQLITE_DENY = 1;
export const SQLITE_IGNORE = 2;
export const SQLITE_CREATE_INDEX = 1;
export const SQLITE_CREATE_TABLE = 2;
export const SQLITE_CREATE_TEMP_INDEX = 3;
export const SQLITE_CREATE_TEMP_TABLE = 4;
export const SQLITE_CREATE_TEMP_TRIGGER = 5;
export const SQLITE_CREATE_TEMP_VIEW = 6;
export const SQLITE_CREATE_TRIGGER = 7;
export const SQLITE_CREATE_VIEW = 8;
export const SQLITE_DELETE = 9;
export const SQLITE_DROP_INDEX = 10;
export const SQLITE_DROP_TABLE = 11;
export const SQLITE_DROP_TEMP_INDEX = 12;
export const SQLITE_DROP_TEMP_TABLE = 13;
export const SQLITE_DROP_TEMP_TRIGGER = 14;
export const SQLITE_DROP_TEMP_VIEW = 15;
export const SQLITE_DROP_TRIGGER = 16;
export const SQLITE_DROP_VIEW = 17;
export const SQLITE_INSERT = 18;
export const SQLITE_PRAGMA = 19;
export const SQLITE_READ = 20;
export const SQLITE_SELECT = 21;
export const SQLITE_TRANSACTION = 22;
export const SQLITE_UPDATE = 23;
export const SQLITE_ATTACH = 24;
export const SQLITE_DETACH = 25;
export const SQLITE_ALTER_TABLE = 26;
export const SQLITE_REINDEX = 27;
export const SQLITE_ANALYZE = 28;
export const SQLITE_CREATE_VTABLE = 29;
export const SQLITE_DROP_VTABLE = 30;
export const SQLITE_FUNCTION = 31;
export const SQLITE_SAVEPOINT = 32;
export const SQLITE_RECURSIVE = 33;

// Event codes for sqlite3_trace_v2.
export const SQLITE_TRACE_STMT = 1;
export const SQLITE_TRACE_PROFILE = 2;
export const SQLITE_TRACE_ROW = 4;
export const SQLITE_TRACE_CLOSE = 8;

// Virtual table constraint operators, scan flags, options and conflict modes.
export const SQLITE_INDEX_SCAN_UNIQUE = 1;
export const SQLITE_INDEX_CONSTRAINT_EQ = 2;
export const SQLITE_INDEX_CONSTRAINT_GT = 4;
export const SQLITE_INDEX_CONSTRAINT_LE = 8;
export const SQLITE_INDEX_CONSTRAINT_LT = 16;
export const SQLITE_INDEX_CONSTRAINT_GE = 32;
export const SQLITE_INDEX_CONSTRAINT_MATCH = 64;
export const SQLITE_INDEX_CONSTRAINT_LIKE = 65;
export const SQLITE_INDEX_CONSTRAINT_GLOB = 66;
export const SQLITE_INDEX_CONSTRAINT_REGEXP = 67;
export const SQLITE_INDEX_CONSTRAINT_NE = 68;
export const SQLITE_INDEX_CONSTRAINT_ISNOT = 69;
export const SQLITE_INDEX_CONSTRAINT_ISNOTNULL = 70;
export const SQLITE_INDEX_CONSTRAINT_ISNULL = 71;
export const SQLITE_INDEX_CONSTRAINT_IS = 72;
export const SQLITE_INDEX_CONSTRAINT_LIMIT = 73;
export const SQLITE_INDEX_CONSTRAINT_OFFSET = 74;
export const SQLITE_INDEX_CONSTRAINT_FUNCTION = 150;
export const SQLITE_VTAB_CONSTRAINT_SUPPORT = 1;
export const SQLITE_VTAB_INNOCUOUS = 2;
export const SQLITE_VTAB_DIRECTONLY = 3;
export const SQLITE_VTAB_USES_ALL_SCHEMAS = 4;
export const SQLITE_ROLLBACK = 1;
export const SQLITE_FAIL = 3;
export const SQLITE_REPLACE = 5;

// Destructors for the functions that bind or return text or a blob.
export const SQLITE_STATIC = 0;
export const SQLITE_TRANSIENT = -1;

/**
 * The function-table index of `sqlite3_free` in this build. Passed as a
 * destructor of text or a blob, it hands the buffer to SQLite, which frees it.
 */
export const SQLITE_WASM_DEALLOC = 1 as SqliteFunctionPtr;

/** The SQLite version of this build. */
export const SQLITE_VERSION = "3.53.4";

/** The SQLite version number of this build. */
export const SQLITE_VERSION_NUMBER = 3053004;

/** The SQLite check-in of this build. */
export const SQLITE_SOURCE_ID =
  "2026-07-24 19:02:57 bf7c7f30031888f4e796e429ab3978879485813aaca6f641c7b33e4e09459bcc";

/** A primary or extended result code. */
export type SqliteResultCode =
  | typeof SQLITE_OK
  | typeof SQLITE_ERROR
  | typeof SQLITE_INTERNAL
  | typeof SQLITE_PERM
  | typeof SQLITE_ABORT
  | typeof SQLITE_BUSY
  | typeof SQLITE_LOCKED
  | typeof SQLITE_NOMEM
  | typeof SQLITE_READONLY
  | typeof SQLITE_INTERRUPT
  | typeof SQLITE_IOERR
  | typeof SQLITE_CORRUPT
  | typeof SQLITE_NOTFOUND
  | typeof SQLITE_FULL
  | typeof SQLITE_CANTOPEN
  | typeof SQLITE_PROTOCOL
  | typeof SQLITE_EMPTY
  | typeof SQLITE_SCHEMA
  | typeof SQLITE_TOOBIG
  | typeof SQLITE_CONSTRAINT
  | typeof SQLITE_MISMATCH
  | typeof SQLITE_MISUSE
  | typeof SQLITE_NOLFS
  | typeof SQLITE_AUTH
  | typeof SQLITE_FORMAT
  | typeof SQLITE_RANGE
  | typeof SQLITE_NOTADB
  | typeof SQLITE_NOTICE
  | typeof SQLITE_WARNING
  | typeof SQLITE_ROW
  | typeof SQLITE_DONE
  | typeof SQLITE_ERROR_MISSING_COLLSEQ
  | typeof SQLITE_ERROR_RETRY
  | typeof SQLITE_ERROR_SNAPSHOT
  | typeof SQLITE_IOERR_READ
  | typeof SQLITE_IOERR_SHORT_READ
  | typeof SQLITE_IOERR_WRITE
  | typeof SQLITE_IOERR_FSYNC
  | typeof SQLITE_IOERR_DIR_FSYNC
  | typeof SQLITE_IOERR_TRUNCATE
  | typeof SQLITE_IOERR_FSTAT
  | typeof SQLITE_IOERR_UNLOCK
  | typeof SQLITE_IOERR_RDLOCK
  | typeof SQLITE_IOERR_DELETE
  | typeof SQLITE_IOERR_BLOCKED
  | typeof SQLITE_IOERR_NOMEM
  | typeof SQLITE_IOERR_ACCESS
  | typeof SQLITE_IOERR_CHECKRESERVEDLOCK
  | typeof SQLITE_IOERR_LOCK
  | typeof SQLITE_IOERR_CLOSE
  | typeof SQLITE_IOERR_DIR_CLOSE
  | typeof SQLITE_IOERR_SHMOPEN
  | typeof SQLITE_IOERR_SHMSIZE
  | typeof SQLITE_IOERR_SHMLOCK
  | typeof SQLITE_IOERR_SHMMAP
  | typeof SQLITE_IOERR_SEEK
  | typeof SQLITE_IOERR_DELETE_NOENT
  | typeof SQLITE_IOERR_MMAP
  | typeof SQLITE_IOERR_GETTEMPPATH
  | typeof SQLITE_IOERR_CONVPATH
  | typeof SQLITE_IOERR_VNODE
  | typeof SQLITE_IOERR_AUTH
  | typeof SQLITE_IOERR_BEGIN_ATOMIC
  | typeof SQLITE_IOERR_COMMIT_ATOMIC
  | typeof SQLITE_IOERR_ROLLBACK_ATOMIC
  | typeof SQLITE_IOERR_DATA
  | typeof SQLITE_IOERR_CORRUPTFS
  | typeof SQLITE_LOCKED_SHAREDCACHE
  | typeof SQLITE_LOCKED_VTAB
  | typeof SQLITE_BUSY_RECOVERY
  | typeof SQLITE_BUSY_SNAPSHOT
  | typeof SQLITE_BUSY_TIMEOUT
  | typeof SQLITE_CANTOPEN_NOTEMPDIR
  | typeof SQLITE_CANTOPEN_ISDIR
  | typeof SQLITE_CANTOPEN_FULLPATH
  | typeof SQLITE_CANTOPEN_CONVPATH
  | typeof SQLITE_CANTOPEN_SYMLINK
  | typeof SQLITE_CORRUPT_VTAB
  | typeof SQLITE_CORRUPT_SEQUENCE
  | typeof SQLITE_CORRUPT_INDEX
  | typeof SQLITE_READONLY_RECOVERY
  | typeof SQLITE_READONLY_CANTLOCK
  | typeof SQLITE_READONLY_ROLLBACK
  | typeof SQLITE_READONLY_DBMOVED
  | typeof SQLITE_READONLY_CANTINIT
  | typeof SQLITE_READONLY_DIRECTORY
  | typeof SQLITE_ABORT_ROLLBACK
  | typeof SQLITE_CONSTRAINT_CHECK
  | typeof SQLITE_CONSTRAINT_COMMITHOOK
  | typeof SQLITE_CONSTRAINT_FOREIGNKEY
  | typeof SQLITE_CONSTRAINT_FUNCTION
  | typeof SQLITE_CONSTRAINT_NOTNULL
  | typeof SQLITE_CONSTRAINT_PRIMARYKEY
  | typeof SQLITE_CONSTRAINT_TRIGGER
  | typeof SQLITE_CONSTRAINT_UNIQUE
  | typeof SQLITE_CONSTRAINT_VTAB
  | typeof SQLITE_CONSTRAINT_ROWID
  | typeof SQLITE_CONSTRAINT_PINNED
  | typeof SQLITE_CONSTRAINT_DATATYPE
  | typeof SQLITE_NOTICE_RECOVER_WAL
  | typeof SQLITE_NOTICE_RECOVER_ROLLBACK
  | typeof SQLITE_WARNING_AUTOINDEX
  | typeof SQLITE_AUTH_USER
  | typeof SQLITE_OK_LOAD_PERMANENTLY;

/**
 * A primary result code, the low 8 bits of an extended one. SQLITE_ROW and
 * SQLITE_DONE are primary codes too.
 */
export type SqlitePrimaryResultCode =
  | typeof SQLITE_OK
  | typeof SQLITE_ERROR
  | typeof SQLITE_INTERNAL
  | typeof SQLITE_PERM
  | typeof SQLITE_ABORT
  | typeof SQLITE_BUSY
  | typeof SQLITE_LOCKED
  | typeof SQLITE_NOMEM
  | typeof SQLITE_READONLY
  | typeof SQLITE_INTERRUPT
  | typeof SQLITE_IOERR
  | typeof SQLITE_CORRUPT
  | typeof SQLITE_NOTFOUND
  | typeof SQLITE_FULL
  | typeof SQLITE_CANTOPEN
  | typeof SQLITE_PROTOCOL
  | typeof SQLITE_EMPTY
  | typeof SQLITE_SCHEMA
  | typeof SQLITE_TOOBIG
  | typeof SQLITE_CONSTRAINT
  | typeof SQLITE_MISMATCH
  | typeof SQLITE_MISUSE
  | typeof SQLITE_NOLFS
  | typeof SQLITE_AUTH
  | typeof SQLITE_FORMAT
  | typeof SQLITE_RANGE
  | typeof SQLITE_NOTADB
  | typeof SQLITE_NOTICE
  | typeof SQLITE_WARNING
  | typeof SQLITE_ROW
  | typeof SQLITE_DONE;

/** A fundamental data type, which sqlite3_column_type returns. */
export type SqliteDataType =
  | typeof SQLITE_INTEGER
  | typeof SQLITE_FLOAT
  | typeof SQLITE_TEXT
  | typeof SQLITE_BLOB
  | typeof SQLITE_NULL;

/** A file lock level of the VFS xLock and xUnlock methods. */
export type SqliteLockLevel =
  | typeof SQLITE_LOCK_NONE
  | typeof SQLITE_LOCK_SHARED
  | typeof SQLITE_LOCK_RESERVED
  | typeof SQLITE_LOCK_PENDING
  | typeof SQLITE_LOCK_EXCLUSIVE;

/** The layout of `sqlite3_vfs` in this wasm build. */
export const sqlite3_vfs_layout = {
  sizeof: 88,
  members: {
    iVersion: { offset: 0, signature: "i" },
    szOsFile: { offset: 4, signature: "i" },
    mxPathname: { offset: 8, signature: "i" },
    pNext: { offset: 12, signature: "p" },
    zName: { offset: 16, signature: "s" },
    pAppData: { offset: 20, signature: "p" },
    xOpen: { offset: 24, signature: "i(pppip)" },
    xDelete: { offset: 28, signature: "i(ppi)" },
    xAccess: { offset: 32, signature: "i(ppip)" },
    xFullPathname: { offset: 36, signature: "i(ppip)" },
    xDlOpen: { offset: 40, signature: "v(pp)" },
    xDlError: { offset: 44, signature: "v(pip)" },
    xDlSym: { offset: 48, signature: "p()" },
    xDlClose: { offset: 52, signature: "v(pp)" },
    xRandomness: { offset: 56, signature: "i(pip)" },
    xSleep: { offset: 60, signature: "i(pi)" },
    xCurrentTime: { offset: 64, signature: "i(pp)" },
    xGetLastError: { offset: 68, signature: "i(pip)" },
    xCurrentTimeInt64: { offset: 72, signature: "i(pp)" },
    xSetSystemCall: { offset: 76, signature: "i(ppp)" },
    xGetSystemCall: { offset: 80, signature: "p(pp)" },
    xNextSystemCall: { offset: 84, signature: "p(pp)" },
  },
} as const;

/** The layout of `sqlite3_io_methods` in this wasm build. */
export const sqlite3_io_methods_layout = {
  sizeof: 76,
  members: {
    iVersion: { offset: 0, signature: "i" },
    xClose: { offset: 4, signature: "i(p)" },
    xRead: { offset: 8, signature: "i(ppij)" },
    xWrite: { offset: 12, signature: "i(ppij)" },
    xTruncate: { offset: 16, signature: "i(pj)" },
    xSync: { offset: 20, signature: "i(pi)" },
    xFileSize: { offset: 24, signature: "i(pp)" },
    xLock: { offset: 28, signature: "i(pi)" },
    xUnlock: { offset: 32, signature: "i(pi)" },
    xCheckReservedLock: { offset: 36, signature: "i(pp)" },
    xFileControl: { offset: 40, signature: "i(pip)" },
    xSectorSize: { offset: 44, signature: "i(p)" },
    xDeviceCharacteristics: { offset: 48, signature: "i(p)" },
    xShmMap: { offset: 52, signature: "i(piiip)" },
    xShmLock: { offset: 56, signature: "i(piii)" },
    xShmBarrier: { offset: 60, signature: "v(p)" },
    xShmUnmap: { offset: 64, signature: "i(pi)" },
    xFetch: { offset: 68, signature: "i(pjip)" },
    xUnfetch: { offset: 72, signature: "i(pjp)" },
  },
} as const;

/** The layout of `sqlite3_file` in this wasm build. */
export const sqlite3_file_layout = {
  sizeof: 4,
  members: {
    pMethods: { offset: 0, signature: "p" },
  },
} as const;

/** The layout of `sqlite3_module` in this wasm build. */
export const sqlite3_module_layout = {
  sizeof: 100,
  members: {
    iVersion: { offset: 0, signature: "i" },
    xCreate: { offset: 4, signature: "i(ppippp)" },
    xConnect: { offset: 8, signature: "i(ppippp)" },
    xBestIndex: { offset: 12, signature: "i(pp)" },
    xDisconnect: { offset: 16, signature: "i(p)" },
    xDestroy: { offset: 20, signature: "i(p)" },
    xOpen: { offset: 24, signature: "i(pp)" },
    xClose: { offset: 28, signature: "i(p)" },
    xFilter: { offset: 32, signature: "i(pisip)" },
    xNext: { offset: 36, signature: "i(p)" },
    xEof: { offset: 40, signature: "i(p)" },
    xColumn: { offset: 44, signature: "i(ppi)" },
    xRowid: { offset: 48, signature: "i(pp)" },
    xUpdate: { offset: 52, signature: "i(pipp)" },
    xBegin: { offset: 56, signature: "i(p)" },
    xSync: { offset: 60, signature: "i(p)" },
    xCommit: { offset: 64, signature: "i(p)" },
    xRollback: { offset: 68, signature: "i(p)" },
    xFindFunction: { offset: 72, signature: "i(pispp)" },
    xRename: { offset: 76, signature: "i(ps)" },
    xSavepoint: { offset: 80, signature: "i(pi)" },
    xRelease: { offset: 84, signature: "i(pi)" },
    xRollbackTo: { offset: 88, signature: "i(pi)" },
    xShadowName: { offset: 92, signature: "i(s)" },
    xIntegrity: { offset: 96, signature: "i(pppip)" },
  },
} as const;

/** The layout of `sqlite3_vtab` in this wasm build. */
export const sqlite3_vtab_layout = {
  sizeof: 12,
  members: {
    pModule: { offset: 0, signature: "p" },
    nRef: { offset: 4, signature: "i" },
    zErrMsg: { offset: 8, signature: "p" },
  },
} as const;

/** The layout of `sqlite3_vtab_cursor` in this wasm build. */
export const sqlite3_vtab_cursor_layout = {
  sizeof: 4,
  members: {
    pVtab: { offset: 0, signature: "p" },
  },
} as const;

/** The layout of `sqlite3_index_info` in this wasm build. */
export const sqlite3_index_info_layout = {
  sizeof: 72,
  members: {
    nConstraint: { offset: 0, signature: "i" },
    aConstraint: { offset: 4, signature: "p" },
    nOrderBy: { offset: 8, signature: "i" },
    aOrderBy: { offset: 12, signature: "p" },
    aConstraintUsage: { offset: 16, signature: "p" },
    idxNum: { offset: 20, signature: "i" },
    idxStr: { offset: 24, signature: "p" },
    needToFreeIdxStr: { offset: 28, signature: "i" },
    orderByConsumed: { offset: 32, signature: "i" },
    estimatedCost: { offset: 40, signature: "d" },
    estimatedRows: { offset: 48, signature: "j" },
    idxFlags: { offset: 56, signature: "i" },
    colUsed: { offset: 64, signature: "j" },
  },
} as const;

/** The layout of `sqlite3_index_constraint` in this wasm build. */
export const sqlite3_index_constraint_layout = {
  sizeof: 12,
  members: {
    iColumn: { offset: 0, signature: "i" },
    op: { offset: 4, signature: "C" },
    usable: { offset: 5, signature: "C" },
    iTermOffset: { offset: 8, signature: "i" },
  },
} as const;

/** The layout of `sqlite3_index_orderby` in this wasm build. */
export const sqlite3_index_orderby_layout = {
  sizeof: 8,
  members: {
    iColumn: { offset: 0, signature: "i" },
    desc: { offset: 4, signature: "C" },
  },
} as const;

/** The layout of `sqlite3_index_constraint_usage` in this wasm build. */
export const sqlite3_index_constraint_usage_layout = {
  sizeof: 8,
  members: {
    argvIndex: { offset: 0, signature: "i" },
    omit: { offset: 4, signature: "C" },
  },
} as const;

/**
 * Identifies the build these constants and the CApi functions describe.
 *
 * The 32-bit FNV-1a hash (offset basis 0x811c9dc5, prime 0x01000193) of these
 * bytes, which a loader reads from the instance and the compiled module:
 *
 * 1. The string `sqlite3__wasm_enum_json()` returns: its UTF-8 bytes including the
 *    terminating NUL.
 * 2. The name of every export `WebAssembly.Module.exports` lists, in the order
 *    `toSorted()` without a comparator gives: for each, its UTF-8 bytes
 *    followed by a NUL byte.
 *
 * The string holds SQLite's version and check-in, every constant and the struct
 * layouts, and the names include every function and shim the CApi module reads.
 * The hash covers neither code nor function types; the generator checks every
 * binding's and shim's wasm type against the pinned build, and
 * `scripts/generate.mts --verify-build` checks a binary against the pins.
 */
export const sqliteWasmBuildHash = 0xc5cfb5b8;
