name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - shell: bash
      run: corepack enable

    - shell: bash
      run: pnpm install --frozen-lockfile